### ISSUE TITLE
Page Does Not Work

### ISSUE THREAD

**Issue by AdolfotULS** [Vkrsi/code-screenshot#1]
It's blank and I can't do anything

![image](https://github.com/Vkrsi/code-screenshot/assets/166766031/c8fbb8e9-4971-4d69-8e93-f924ea545fad)

**Comment by rahulkumarsingh73690** [comment]
Please go to site setting and delete data or try in incognito window

**Comment by rahulkumarsingh73690** [comment]
Working on all devices and browsers. Tested using [browserling/](https://www.browserling.com/)

**Comment by AdolfotULS** [comment]
Same thing, tried in Opera and Edge, both in incognito mode, deleted cookies, still blank.

**Comment by AdolfotULS** [comment]
![image](https://github.com/Vkrsi/code-screenshot/assets/166766031/552ace68-5410-41e6-8854-689438777ec5)
We tested in different browsers among different people, all from Chile, CL. And we all see a blank page.

**Comment by AdolfotULS** [comment]
![image](https://github.com/Vkrsi/code-screenshot/assets/166766031/a271aac1-6ee7-4619-9b96-158fbe6bb81e)

**Comment by AdolfotULS** [comment]
Test Link: https://cs.vkrsi.com/?language=c++&code=%257D%250D%250ADigito*%2520invertirLista(Digito*%2520lista)%2520%257B%250D%250A%2520%2520%2520%2520Digito*%2520invertido%2520%253D%2520NULL%253B%250D%250A%2520%2520%2520%2520Digito*%2520actual%2520%253D%2520lista%253B%250D%250A%250D%250A%2520%2520%2520%2520while%2520(actual%2520!%253D%2520NULL)%2520%257B%250D%250A%2520%2520%2520%2520%2520%2520%2520%2520Digito*%2520nuevoDigito%2520%253D%2520(Digito*)malloc(sizeof(Digito))%253B%250D%250A%2520%2520%2520%2520%2520%2520%2520%2520nuevoDigito-%253Evalor%2520%253D%2520actual-%253Evalor%253B%250D%250A%2520%2520%2520%2520%2520%2520%2520%2520nuevoDigito-%253Esiguiente%2520%253D%2520invertido%253B%250D%250A%2520%2520%2520%2520%2520%2520%2520%2520invertido%2520%253D%2520nuevoDigito%253B%250D%250A%2520%2520%2520%2520%2520%2520%2520%2520actual%2520%253D%2520actual-%253Esiguiente%253B%250D%250A%2520%2520%2520%2520%257D%250D%250A%250D%250A%2520%2520%2520%2520return%2520invertido%253B%250D%250A%257D&title=lista_enlazada.h&ref=vscode

**Comment by rahulkumarsingh73690** [comment]
Thanks for sharing, it look like this issue is related to vs code extension. Let me check and fix it asap.

**Comment by rahulkumarsingh73690** [comment]
Fixed in vs code extension version 1.0.4. 

Please update and let me know if you still face any issues, make sure you don't use the existing URL. Use latest URL generated by extesnion

**Comment by AdolfotULS** [comment]
It already works, we checked it among several people, however sometimes when closing the browser it stops working and you have to delete all Cookies, in my personal case it does not work in Microsoft Edge but other people do.

**Comment by AdolfotULS** [comment]
I think I found the solution and it is for a particular cookie, I did the tests and now it works:
The problem is that in the Edge does not let me delete the cookie "cs.vkrsi.com" which is the one that eliminating it lets the page work correctly.

Edge Cookies Image
![image](https://github.com/Vkrsi/code-screenshot/assets/166766031/249442f0-5fcb-4c3b-9037-279b35f4d04e)

Opera Cookies image
![image](https://github.com/Vkrsi/code-screenshot/assets/166766031/be098868-9f6d-4aa7-953c-eaaf04884f7b)

To fix the problem I installed a random extension to delete cookies in this case: 
 https://microsoftedge.microsoft.com/addons/detail/cookie-autodelete/djkjpnciiommncecmdefpdllknjdmmmo

**Comment by AdolfotULS** [comment]
Sorry for the images in Spanish, but they are understandable.

**Comment by rahulkumarsingh73690** [comment]
> It already works, we checked it among several people, however sometimes when closing the browser it stops working and you have to delete all Cookies, in my personal case it does not work in Microsoft Edge but other people do.

Please open console and share screenshot

**Comment by AdolfotULS** [comment]
These pictures are taken after I cleared the cookies in Edge and it worked fine.

Console:
![image](https://github.com/Vkrsi/code-screenshot/assets/166766031/891c5821-9151-4504-b1dd-4f330026c733)

Elements:
![image](https://github.com/Vkrsi/code-screenshot/assets/166766031/07cd474b-60b4-4d8a-a3d6-414f53198bea)

In this part when I had trouble with the Cookies, the <div id="root"> part was found without content, that is, completely empty.
![image](https://github.com/Vkrsi/code-screenshot/assets/166766031/471b2f95-3535-4d52-987b-a51b8fda5492)

**Comment by AdolfotULS** [comment]
I forgot this photo
![image](https://github.com/Vkrsi/code-screenshot/assets/166766031/e0870cfb-236d-4306-a685-e5df5b999243)

**Comment by rahulkumarsingh73690** [comment]
> In this part when I had trouble with the Cookies, the [div id="root"] part was found without content, that is, completely empty.

No content is available see ...

Looks good as per the current image, when the site breaks then take a snapshot. Latest VS code extension fixed all issue

**Comment by AdolfotULS** [comment]
Everything works fine so far, it is solved, thanks for the help.
