### ISSUE TITLE
Web page only shows help, not the selected code

### ISSUE THREAD

**Issue by Maddimax** [Vkrsi/code-screenshot#3]
Doesn't work anymore for an hour or so it seems.

**Comment by rahulkumarsingh73690** [comment]
What do you mean? Can you please share screenshot?

**Comment by Maddimax** [comment]
Try https://cs.vkrsi.com/?autoDetectLanguage=true&code=%252F*%2520Callback%2520from%2520macOS%2520that%2520the%2520application%2520should%2520handle%2520a%2520URL%2520*%252F%250Abool%2520QCocoaServices%253A%253AhandleUrl(const%2520QUrl%2520%2526url)%250A%257B%250A%2520%2520%2520%2520QScopedValueRollback%253CQUrl%253E%2520rollback(m_handlingUrl%252C%2520url)%253B%250A%2520%2520%2520%2520%252F%252F%2520FIXME%253A%2520Add%2520platform%2520services%2520callback%2520from%2520QDesktopServices%253A%253AsetUrlHandler%250A%2520%2520%2520%2520%252F%252F%2520so%2520that%2520we%2520can%2520warn%2520the%2520user%2520if%2520calling%2520setUrlHandler%2520without%2520also%2520setting%250A%2520%2520%2520%2520%252F%252F%2520up%2520the%2520matching%2520keys%2520in%2520the%2520Info.plist%2520file%2520(CFBundleURLTypes%2520and%2520friends).%250A%2520%2520%2520%2520return%2520QDesktopServices%253A%253AopenUrl(url)%253B%250A%257D&title=qcocoaservices.mm&ref=vscode

**Comment by Maddimax** [comment]
![image](https://github.com/user-attachments/assets/d46e6bf8-6ccf-4232-9393-5cca2a76cf40)

**Comment by rahulkumarsingh73690** [comment]
Issue fixed, please check and let me know if you still face any issue 😊

**Comment by Maddimax** [comment]
👍 Thanks
